### ISSUE TITLE
DEV, STAGE, PROD 별 CD 스크립트

### ISSUE THREAD

**Issue by jchanho99** [100-hours-a-week/15-Leafresh-CL#9]
### 1. BE DEV CD
```yaml
name: BE CD - DEV

on:
  workflow_run:
    workflows: ["CI BE"]               # ci-be.yml에서 정의한 name
    types:
      - completed
    branches:
      - dev

jobs:
  deploy-if-ci-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: CD to DEV GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_KEY_DEV }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to DEV GCE
        run: |
          scp -i key.pem -r ./backend user@${{ secrets.DEV_GCE_IP }}:/home/user/backend
          ssh -i key.pem user@${{ secrets.DEV_GCE_IP }} << 'EOF'
            cd /home/user/backend
            chmod +x ./gradlew
            ./gradlew build
            pkill -f 'java -jar' || true
            nohup java -jar ./build/libs/*.jar > app.log 2>&1 &
          EOF
```

---

### 2. BE STAGE, PROD CD
```yaml
name: BE CD - Manual Deploy (STAGE / PROD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포할 환경을 선택하세요 (stage 또는 prod)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod
      version:
        description: '선택적 커밋 또는 태그 (미입력 시 최신 코드 사용)'
        required: false

jobs:
  deploy:
    name: CD to ${{ github.event.inputs.environment | upper }} GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || 'refs/heads/${{ github.event.inputs.environment }}' }}

      - name: Set SSH Key
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            echo "${{ secrets.SSH_KEY_STAGE }}" > key.pem
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "${{ secrets.SSH_KEY_PROD }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Deploy to ${{ github.event.inputs.environment }} GCE
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            HOST=${{ secrets.STAGE_GCE_IP }}
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            HOST=${{ secrets.PROD_GCE_IP }}
          fi

          scp -i key.pem -r ./backend user@$HOST:/home/user/backend
          ssh -i key.pem user@$HOST << 'EOF'
            cd /home/user/backend
            chmod +x ./gradlew
            ./gradlew build
            pkill -f 'java -jar' || true
            nohup java -jar ./build/libs/*.jar > app.log 2>&1 &
          EOF

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Send Discord Notification
        run: |
          STATUS=${{ needs.deploy.result }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "content": "[BE CD] '${{ github.event.inputs.environment }}' 환경 배포 결과: '"$STATUS"' - ${{ github.repository }} @ ${{ github.sha }}"
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
```

---

### 3. FE DEV CD
```yaml
name: FE CD - DEV

on:
  workflow_run:
    workflows: ["CI FE"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy-if-ci-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: CD to DEV GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SSH Key
        run: |
          echo "${{ secrets.SSH_KEY_FE_DEV }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to FE DEV GCE
        run: |
          scp -i key.pem -r ./frontend user@${{ secrets.FE_DEV_GCE_IP }}:/home/user/frontend
          ssh -i key.pem user@${{ secrets.FE_DEV_GCE_IP }} << 'EOF'
            cd /home/user/frontend
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
          EOF
```

---

### 4. FE STAGE, PROD CD
```yaml
name: FE CD - Manual Deploy (STAGE / PROD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포할 환경 (stage 또는 prod)'
        required: true
        type: choice
        options: [stage, prod]
      version:
        description: 'Git 커밋 해시 또는 태그'
        required: false

jobs:
  deploy:
    name: CD to ${{ github.event.inputs.environment | upper }} GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || 'refs/heads/${{ github.event.inputs.environment }}' }}

      - name: Set SSH Key
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            echo "${{ secrets.SSH_KEY_FE_STAGE }}" > key.pem
          else
            echo "${{ secrets.SSH_KEY_FE_PROD }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Deploy to FE ${{ github.event.inputs.environment }} GCE
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            HOST=${{ secrets.FE_STAGE_GCE_IP }}
          else
            HOST=${{ secrets.FE_PROD_GCE_IP }}
          fi

          scp -i key.pem -r ./frontend user@$HOST:/home/user/frontend
          ssh -i key.pem user@$HOST << 'EOF'
            cd /home/user/frontend
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
          EOF

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Send Discord Notification
        run: |
          STATUS=${{ needs.deploy.result }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "content": "[FE CD] '${{ github.event.inputs.environment }}' 환경 배포 결과: '"$STATUS"' - ${{ github.repository }} @ ${{ github.sha }}"
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
```

---

### 5. AI DEV CD
```yaml
name: AI CD - DEV

on:
  workflow_run:
    workflows: ["CI AI"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy-if-ci-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: CD to DEV GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SSH Key
        run: |
          echo "${{ secrets.SSH_KEY_AI_DEV }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to AI DEV GCE
        run: |
          scp -i key.pem -r ./ai user@${{ secrets.AI_DEV_GCE_IP }}:/home/user/ai
          ssh -i key.pem user@${{ secrets.AI_DEV_GCE_IP }} << 'EOF'
            cd /home/user/ai
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f 'uvicorn' || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF
```

---

### 6. AI STAGE, PROD CD
```yaml
name: AI CD - Manual Deploy (STAGE / PROD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포할 환경 (stage 또는 prod)'
        required: true
        type: choice
        options: [stage, prod]
      version:
        description: 'Git 커밋 해시 또는 태그'
        required: false

jobs:
  deploy:
    name: CD to ${{ github.event.inputs.environment | upper }} GCE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || 'refs/heads/${{ github.event.inputs.environment }}' }}

      - name: Set SSH Key
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            echo "${{ secrets.SSH_KEY_AI_STAGE }}" > key.pem
          else
            echo "${{ secrets.SSH_KEY_AI_PROD }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Deploy to AI ${{ github.event.inputs.environment }} GCE
        run: |
          if [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            HOST=${{ secrets.AI_STAGE_GCE_IP }}
          else
            HOST=${{ secrets.AI_PROD_GCE_IP }}
          fi

          scp -i key.pem -r ./ai user@$HOST:/home/user/ai
          ssh -i key.pem user@$HOST << 'EOF'
            cd /home/user/ai
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f 'uvicorn' || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Send Discord Notification
        run: |
          STATUS=${{ needs.deploy.result }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "content": "[AI CD] '${{ github.event.inputs.environment }}' 환경 배포 결과: '"$STATUS"' - ${{ github.repository }} @ ${{ github.sha }}"
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
```
